# Generated by Django 5.2.7 on 2025-11-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adress_line1',
            new_name='adress',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='adress_line2',
        ),
    ]
